services:
  fw:
    image: bin/fw
    build: ./fw
    container_name: fw
    networks:
      external-network: 
        ipv4_address: 10.5.0.1
      DMZ: 
        ipv4_address: 10.5.1.1
      internal-network: 
        ipv4_address: 10.5.2.1
    privileged: true
    tty: true

  dmz1:
    image: bin/dmz1
    build: ./dmz/dmz1
    container_name: dmz1
    networks:
      DMZ:
        ipv4_address: 10.5.1.20
    depends_on:
      - fw
    privileged: true
    tty: true

  dmz2:
    image: bin/dmz2
    build: ./dmz/dmz2
    container_name: dmz2
    networks:
      DMZ:
        ipv4_address: 10.5.1.21
    depends_on:
      - fw
    privileged: true
    tty: true

  int1:
    image: bin/int1
    build: ./internal/int1
    container_name: int1
    networks:
      internal-network:
        ipv4_address: 10.5.2.20
    depends_on:
      - fw
    privileged: true
    tty: true

  int2:
    image: bin/int2
    build: ./internal/int2
    container_name: int2
    networks:
      internal-network:
        ipv4_address: 10.5.2.21
    depends_on:
      - fw
    privileged: true
    tty: true

  int3:
    image: bin/int3
    build: ./internal/int3
    container_name: int3
    networks:
      internal-network:
        ipv4_address: 10.5.2.22
    depends_on:
      - fw
    privileged: true
    tty: true
    

  ext1:
    image: bin/ext
    build: ./external
    container_name: ext
    networks:
      external-network: 
        ipv4_address: 10.5.0.20
    depends_on:
      - fw
    privileged: true
    tty: true

networks:
  external-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/24
        gateway: 10.5.0.254

  DMZ:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.1.0/24
        gateway: 10.5.1.254
  
  internal-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.2.0/24
        gateway: 10.5.2.254